### ISSUE TITLE
RPN ou PN

### ISSUE THREAD

**Issue by hgees** [hgees/calculadoraRPN#1]
O programa deve ser para Notação Polonesa ou para Notação Polonesa Reversa?
Talvez ambos?
debemos tirar tal duvida...

**Comment by rspds** [comment]
Segundo mostrado em sala, foi definido como a reversa. Contudo, se possível faremos a PN, mas por enquanto, o que se pede é a RPN

**Comment by hgees** [comment]
RPN feita... talvez implementamos a PN numa atualização futura, até la... fechado
